Added UI test.
Forfeit76/wdio-js pull request #1
Opened 2021-03-25 17:53 UTC by Forfeit76

2021-03-25 18:40 UTC, Dinerville requested changes
посмотрел пр. с большего хорошо, пару небольших замечаний

2021-03-25 18:40 UTC, Dinerville commented on test/pageobjects/search.page.js
> +    get inputSearch () { return $('.//form//input') }
старайся не использовать xpath, вместо этого используй сss селекторы, главным образом айди
например в данном случае лучшим вариантом был бы селектор `[name='q']`   
в приложении которые мы можем влиять, используй в 99 случаев css с айди, например `#мой_уникальный_айдишник_который_я_попросил_разработчиков_добавить_для_этого_элемента`

2021-03-25 18:40 UTC, Dinerville commented on README.md
> +npx wdio run wdio.conf.js
лучше сделай start скрипт, который будет запускать тесты
чтобы запустить нужно будет `npm start` написать, что легче

2021-03-25 18:40 UTC, Dinerville commented on test/pageobjects/search.page.js
> +    get suggestion () { return $(".//span[contains(text(),'wdio')]") }
старайся методы делать переиспользуемые, грубо говоря тут могло бы быть так
```
(suggestion) => $(`.//span[contains(text(),'${suggestion}')]`)
```

2021-03-25 18:40 UTC, Dinerville commented on test/pageobjects/search.page.js
> +    get introAgreeButton () { return $(".//*[@id='introAgreeButton']") }
css селектор проще return $("#introAgreeButton")

2021-03-25 18:40 UTC, Dinerville commented on test/pageobjects/search.page.js
> +        let iframe = await browser.findElement("xpath", ".//iframe");
айфреймов может быть несколько, находи фрейм по уникальному идентификатору, идеально - айди
сам фрейм сделай методом вверху, как ты сделал все остальное

2021-03-25 18:40 UTC, Dinerville commented on test/pageobjects/search.page.js
> +    get inputSearch () { return $('.//form//input') }
гетеры могут запоминать свое состояние и не вычислять еще раз уже известное значение
![image](https://user-images.githubusercontent.com/18195829/112524591-4a8d7380-8da0-11eb-8b47-6d8b5c28fe86.png)
это значит, что он может не стать вычислять положение элемента второй раз и вернет тебе предыдущий найденый элемент, если ты захочешь вызвать этот элемент несколько раз

лучше используй обычные методы
если хочешь работать с классами, используй конструктор
```
constructor(){
   this.inputSearch = ()=> ($(`[name='q']`))
}
```

2021-03-25 18:40 UTC, Dinerville commented on test/pageobjects/search.page.js
> +    get inputSearch () { return $('.//form//input') }
с гетерами тебе нужно будет каждый раз удалять значение предыдущего гетера
![image](https://user-images.githubusercontent.com/18195829/112525173-e8813e00-8da0-11eb-82e4-c96ea6c33b7f.png)

2021-03-25 18:40 UTC, Dinerville commented on test/pageobjects/webdriverio.main.page.js
> +        fs.writeFile('cookie.txt', JSON.stringify(cookie), function (err) {
лучше использовать синхронный вариант тут writeFileSync

2021-03-25 18:40 UTC, Dinerville commented on test/specs/google.seach.js
> +        await SearchPage.openMainPage();
лучше избавиться от асинхронности и запускать тесты в синхронном моде
тут подробнее
https://webdriver.io/docs/sync-vs-async/

2021-03-25 18:40 UTC, Dinerville commented on wdio.conf.js
> +     * Hook that gets executed _before_ a hook within the suite starts (e.g. runs before calling
удаляй комментарии, легче читать

2021-03-28 16:35 UTC, Forfeit76 commented on test/pageobjects/search.page.js
> +    get inputSearch () { return $('.//form//input') }
"в данном случае лучшим вариантом был бы селектор [name='q']"
что-то я это не совсем понял

2021-04-05 07:30 UTC, Dinerville approved these changes

2021-04-05 07:30 UTC, Dinerville commented on test/pageobjects/google.page.js
> +        browser.setWindowSize(1600, 900);
browser.setWindowSize(1600, 900);

fyi это лучше вынести в beforeScenario хук в wdio.conf.js

2021-04-05 07:30 UTC, Dinerville commented on test/pageobjects/google.page.js
> +        browser.setWindowSize(1600, 900);
чтобы разные можно было легко тестировать мобильное вью и никакие методы не переключались из него случайно

2021-04-19 12:33 UTC, merged